### ISSUE TITLE
Mastodon : automatiser l'export des listes et comptes sur un dépôt dédié

### ISSUE THREAD

**Issue by Guts** [geotribu/cli#177]
C'est plutôt la suite de l'article https://geotribu.fr/articles/2024/2024-02-16_de-twitter-a-mastodon-guide-geo-import-liste-comptes/

L'idée globale est d'utiliser https://cli.geotribu.fr/usage/examples.html#exporter-les-donnees-du-compte-mastodon dans une GitHub Action qui se lance manuellement et régulièrement pour héberger les listes et comptes à télécharger dans l'article. Histoire que ça reste à jour et que le seul travail soit de MAJ les listes depuis Mastodon.

Pour ce qui est de github action, le trigger manuel et régulier peut être copié/collé depuis https://github.com/geotribu/ign-fr-opendata-download-ui/blob/main/.github/workflows/run_n_publish.yml#L3-L10

@gounux ça t'intéresse ?

**Comment by Guts** [comment]
Ah non, je pense qu'on peut plutôt pousser sur les GitHub Pages du projet. Puis on vire les fichiers du CDN et on MAJ les liens dans l'article.

**Comment by Guts** [comment]
Y'a pas d'API sur le CDN. C'est un autre projet : en faire une ou changer d'outil.

**Comment by Guts** [comment]
Plutôt dans un dépôt dédié je pense @gounux

**Comment by gounux** [comment]
ok @Guts, je peux me charger de créer le dépôt

- "mastodon-exports" ?
- quelle licence ?

**Comment by Guts** [comment]
geo-mastodon-comptes-listes ?

**Comment by Guts** [comment]
Vu que c'est pas du code mais du contenu, ce serait plutôt une Creative Commons avec une attribution a minima.

Sinon sous odbl pour encourager/cadrer le reversement des modifs ?

**Comment by Guts** [comment]
Géré par @gounux ici https://github.com/geotribu/geo-mastodon-comptes-listes/pull/1
